#!/usr/bin/env ruby

=begin

Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

answer: 4613732

=end

fibonacci_numbers = Enumerator.new do |yielder|
  f1 = f2 = 1
  loop do
    yielder << f1
    f1, f2 = f2, (f1 + f2)
  end
end

answer =  fibonacci_numbers
  .take_while { |n| n < 4e6 }
  .select(&:even?)
  .inject :+

puts answer
