#!/usr/bin/env ruby

=begin

Problem 12
08 March 2002

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?

answer: 76576500

=end

class Integer

  def divisors_count
    srt = Math.sqrt(self)
    count = 2 * (1..(srt.to_i)).count { |i| (self % i).zero? }
    count -= 1 if srt.integer?
    count
  end

end

triangle_numbers = Enumerator.new do |yielder|
  n = 1
  loop do
    yielder << n * (n + 1) / 2
    n += 1
  end
end

answer = triangle_numbers.find { |t| t.divisors_count > 500 }

puts answer
