#!/usr/bin/env ruby

=begin

Problem 44 23 May 2003

Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70
- 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of
D?

answer: 5482660

=end

class Integer

  def pentagonal?
    a = (1+Math.sqrt(1+24*self))/6
    a == a.to_i
  end

end

pentagonal_numbers = Enumerator.new do |yielder|
  n = 1
  loop do
    yielder << n * (3 * n - 1) / 2
    n += 1
  end
end

# number '2500' guessed
answer = pentagonal_numbers.first(2500).combination(2) do |a, b|
  break (a - b).abs if (a+b).pentagonal? and (a - b).abs.pentagonal?
end

puts answer
