#!/usr/bin/env ruby

=begin

Problem 45
06 June 2003

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

| Triangle   | Tn=n(n+1)/2  | 1, 3, 6, 10, 15, ...  |
| Pentagonal | Pn=n(3n-1)/2 | 1, 5, 12, 22, 35, ... |
| Hexagonal  | Hn=n(2n-1)   | 1, 6, 15, 28, 45, ... |

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

answer: 1533776805

=end

class Integer

  def triangle?
    a = (1+Math.sqrt(1+8*self))/2
    a == a.to_i
  end

  def pentagonal?
    a = (1+Math.sqrt(1+24*self))/6
    a == a.to_i
  end

end

hexagonal_numbers = Enumerator.new do |yielder|
  n = 1
  loop do
    yielder << n * (2 * n - 1)
    n +=1
  end
end

answer = hexagonal_numbers.each do |n|
  break n if n > 40755 and n.pentagonal? and n.triangle?
end

puts answer
